//
//  NSManagedObject+CBDActiveRecord.h
//  MyCBDCoreDataToolKit
//
//  Created by Colas on 10/02/2014.
//  Copyright (c) 2014 Colas. All rights reserved.
//Copyright (c) 2012 Víctor Pena Placer (@vicpenap) http://www.victorpena.es/
//
//Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
//The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.



#import <CoreData/CoreData.h>


/**
 Handy methods to fetch/count/remove  `NSManagedObject` of an caller class.
 */
@interface NSManagedObject (CBDActiveRecord)






#pragma mark - Entité associée
/// @name Associated caller class

/**
 @warning This method only works if:
 
  - the class method
 `+ (NSString *)entityName`
 is implemented in the subclass of `NSManagedObject` from where it is called. This is the case for the classes generated by `mogenerator`.

  - or: if the subclass of `NSManagedObject` from where it is called has the same name as the Entity
 
 We will call in this documentation this condition : "condition `name(Class)=name(Entity)` or `mogenerator`"
 
 Otherwise, it will throw an exception.
 */
+ (NSEntityDescription *)entityInMOC_cbd_:(NSManagedObjectContext *)theMOC ;


#pragma mark - Getting
/// @name Getting objects

/**
 Fetches all the NSManagedObject of a given caller class in the MOC.
 
  @warning This method works only if condition "`name(Class)=name(Entity)` or `mogenerator`" is satisfied
 */
+ (NSArray *)allInMOC_cbd_:(NSManagedObjectContext *)theMOC ;

/*
 *******
 Exemple de orderBy :
 person.name asc, person.age desc
 
 
 Returns an array of sort descriptors based on the SQL-like string passed
 as parameter.
 
 Usage:
 
 You can pass an order-by clause just like in SQL. Syntax expected:
 property [asc|desc][, property [asc|desc]][, ...]
 
 Examples:
 - date
 - date asc
 - date desc, title, id asc
 
 *******
 */


/**
 Fetches all the NSManagedObject of a given caller class in the MOC, ordered.
 
 @param (NSString *)orderBy A SQL-like string
 
 Example of orderBy :
 `person.name asc`, `person.age desc`
 
 Returns an array of sort descriptors based on the SQL-like string passed
 as parameter.
 
 Usage:
 
 You can pass an order-by clause just like in SQL. Syntax expected:
 property [asc|desc][, property [asc|desc]][, ...]
 
 Examples:
 - `date`
 - `date asc`
 - `date desc`, `title`, `id asc`
 
  @warning This method works only if condition "`name(Class)=name(Entity)` or `mogenerator`" is satisfied
 */
+ (NSArray *)allInMOC:(NSManagedObjectContext *)theMOC
       orderedBy_cbd_:(NSString *)orderBy ;



/**
 The first instance in the fetch
 
  @warning This method works only if condition "`name(Class)=name(Entity)` or `mogenerator`" is satisfied
 */
+ (instancetype) firstInMOC:(NSManagedObjectContext *)theMOC
                  orderedBy:(NSString *)orderBy
         withPredicate_cbd_:(NSPredicate *)predicate ;


/**
 The first instance in the fetch
 
 @param (NSString *)formatString Instead of building an `NSPredicate` with `[NSPredicate predicateWithFormat:...`, you can pass the format string directly here.
 
  @warning This method works only if condition "`name(Class)=name(Entity)` or `mogenerator`" is satisfied
 */
+ (instancetype) firstInMOC:(NSManagedObjectContext *)theMOC
                  orderedBy:(NSString *)orderBy
   withPredicateFormat_cbd_:(NSString *)formatString, ... NS_FORMAT_FUNCTION(3, 4) ;


/**
 Does a fetch.
 
  @warning This method works only if condition "`name(Class)=name(Entity)` or `mogenerator`" is satisfied
 */
+ (NSArray *)        findInMOC:(NSManagedObjectContext *)theMOC
            withPredicate_cbd_:(NSPredicate *)predicate ;


/**
 Does a fetch.
 
 @param (NSString *)formatString Instead of building an `NSPredicate` with `[NSPredicate predicateWithFormat:...`, you can pass the format string directly here.
 
  @warning This method works only if condition "`name(Class)=name(Entity)` or `mogenerator`" is satisfied
 */
+ (NSArray *)      findInMOC:(NSManagedObjectContext *)theMOC
    withPredicateFormat_cbd_:(NSString *)formatString, ... NS_FORMAT_FUNCTION(2, 3) ;





/** Returns objects from the caller class.
 
 @param predicate the predicate to filter with.
 @param orderBy an SQL-like order by clause.
 
  @warning This method works only if condition "`name(Class)=name(Entity)` or `mogenerator`" is satisfied
 */
+ (NSArray *) findInMOC:(NSManagedObjectContext *)theMOC
              orderedBy:(NSString *)orderBy
     withPredicate_cbd_:(NSPredicate *)predicate ;


/** Returns objects from the caller class.
 
 @param predicate the predicate to filter with.
 @param orderBy an SQL-like order by clause.
 @param (NSString *)formatString Instead of building an `NSPredicate` with `[NSPredicate predicateWithFormat:...`, you can pass the format string directly here.
 
  @warning This method works only if condition "`name(Class)=name(Entity)` or `mogenerator`" is satisfied
 */
+ (NSArray *)    findInMOC:(NSManagedObjectContext *)theMOC
                 orderedBy:(NSString *)orderBy
  withPredicateFormat_cbd_:(NSString *)formatString, ... NS_FORMAT_FUNCTION(3, 4) ;




/** Returns objects from the caller class.
 
 @param predicate the predicate to filter with.
 @param orderBy an SQL-like order by clause.
 @param offset the index of the first element to retrieve.
 @param limit the maximum amount of objects to retrieve.
 
 @warning This method works only if condition "`name(Class)=name(Entity)` or `mogenerator`" is satisfied
 */
+ (NSArray *) findInMOC:(NSManagedObjectContext *)theMOC
              orderedBy:(NSString *)orderBy
                 offset:(int)offset
                  limit:(int)limit
     withPredicate_cbd_:(NSPredicate *)predicate ;

/** Returns objects from the caller class.
 
 @param predicate the predicate to filter with.
 @param orderBy an SQL-like order by clause.
 @param offset the index of the first element to retrieve.
 @param limit the maximum amount of objects to retrieve.
 @param (NSString *)formatString Instead of building an `NSPredicate` with `[NSPredicate predicateWithFormat:...`, you can pass the format string directly here.

  @warning This method works only if condition "`name(Class)=name(Entity)` or `mogenerator`" is satisfied
 */
+ (NSArray *)       findInMOC:(NSManagedObjectContext *)theMOC
                    orderedBy:(NSString *)orderBy
                       offset:(int)offset
                        limit:(int)limit
     withPredicateFormat_cbd_:(NSString *)formatString, ... NS_FORMAT_FUNCTION(5, 6) ;






#pragma mark - Counting
/// @name Counting



/** Returns the total amount of the objects from the caller class. 
 
  @warning This method works only if condition "`name(Class)=name(Entity)` or `mogenerator`" is satisfied
 */
+ (NSUInteger) countInMOC_cbd_:(NSManagedObjectContext *)theMOC ;
;

/** Returns the total amount of the objects from the caller class.
 
 @param predicate the predicate to filter with. 
 
  @warning This method works only if condition "`name(Class)=name(Entity)` or `mogenerator`" is satisfied*/
+ (NSUInteger) countInMOC:(NSManagedObjectContext *)theMOC
        forPredicate_cbd_:(NSPredicate *)predicate ;

/** Returns the total amount of the objects from the caller class.
 
 @param predicate the predicate to filter with.
 @param (NSString *)formatString Instead of building an `NSPredicate` with `[NSPredicate predicateWithFormat:...`, you can pass the format string directly here.
 
  @warning This method works only if condition "`name(Class)=name(Entity)` or `mogenerator`" is satisfied*/
+ (NSUInteger)     countInMOC:(NSManagedObjectContext *)theMOC
      forPredicateFormat_cbd_:(NSString *)formatString, ... NS_FORMAT_FUNCTION(2, 3) ;







#pragma mark - Removing
/// @name Removing



/** Removes the calling object. */
- (void) remove_cbd_ ;


/** Removes all objects from the caller class. 
 
  @warning This method works only if condition "`name(Class)=name(Entity)` or `mogenerator`" is satisfied
 */
+ (void) removeAllInMOC_cbd_:(NSManagedObjectContext *)theMOC ;
;




#pragma mark - Refetching
/// @name Removing


/** Refetches the object. */
- (instancetype) refetch_cbd_;




#pragma mark - Looking for similar objects
/// @name Looking for similar objects


/**
 Finds objects similar to self, according to attributes and relationships given in the arguments.
 You can specify additionnal constraints with dicoOfFixedAttributesOrRelationships
 
 Example
 
 ```
 [me findSimilarObjectsForAttributes:@[@"age", @"city"]
                    forRelationships:nil
       withAttributesOrRelationships:@{@"isMale" : @NO}] ;
 ```
 will look for `Person`s who have the same `age` as me, who live in the same `city` and with `isMale` attribute equal to `@NO`.
 
  @warning This method works only if condition "`name(Class)=name(Entity)` or `mogenerator`" is satisfied
 
 @warning deprecated since v2.0.0
 */
- (NSArray *)findSimilarObjectsForAttributes:(NSArray *)arrayOfNamesOfAttributes
                            forRelationships:(NSArray *)arrayOfNamesOfRelationships
          withAttributesOrRelationships_cbd_:(NSDictionary *)dicoOfFixedAttributesOrRelationships ;


/**
 Finds objects similar to self, according to attributes and relationships given in the arguments.
 You can specify additionnal constraints with dicoOfFixedAttributesOrRelationships
 
 Does the fetch in a MOC that you can specify.
 
 @warning This method works only if condition "`name(Class)=name(Entity)` or `mogenerator`" is satisfied
 
 @warning deprecated since v2.0.0
 */
- (NSArray *)               findInMOC:(NSManagedObjectContext *)aDifferentMOC
          similarObjectsForAttributes:(NSArray *)arrayOfNamesOfAttributes
                     forRelationships:(NSArray *)arrayOfNamesOfRelationships
   withAttributesOrRelationships_cbd_:(NSDictionary *)dicoOfFixedAttributesOrRelationships ;

/**
 Finds objects similar to self, according to attributes and relationships given in the arguments.
 You can specify additionnal constraints with additionalPredicate
 
 Example
 
 ```
 [me findSimilarObjectsForAttributes:@[@"age", @"city"]
 forRelationships:nil
 withAdditionalPredicate_cbd_:[NSPredicate predicateWithFormat:@"isMale == NO"]] ;
 ```
 will look for `Person`s who have the same `age` as me, who live in the same `city` and with `isMale` attribute equal to `@NO`.
 
 @warning This method works only if condition "`name(Class)=name(Entity)` or `mogenerator`" is satisfied
 
 @warning deprecated since v2.0.0
 */
- (NSArray *)findSimilarObjectsForAttributes:(NSArray *)arrayOfNamesOfAttributes
                            forRelationships:(NSArray *)arrayOfNamesOfRelationships
                withAdditionalPredicate_cbd_:(NSPredicate *)additionalPredicate ;


/**
 Finds objects similar to self, according to attributes and relationships given in the arguments.
 You can specify additionnal constraints with additionalPredicate in a format version.
 */
- (NSArray *)findSimilarObjectsForAttributes:(NSArray *)arrayOfNamesOfAttributes
                            forRelationships:(NSArray *)arrayOfNamesOfRelationships
          withAdditionalPredicateFormat_cbd_:(NSString *)formatString, ... NS_FORMAT_FUNCTION(3, 4) ;

/**
 Finds objects similar to self, according to attributes and relationships given in the arguments.
 You can specify additionnal constraints with additionalPredicate.
 
 Does the fetch in a MOC that you can specify.
 
 @warning This method works only if condition "`name(Class)=name(Entity)` or `mogenerator`" is satisfied
 
 @warning deprecated since v2.0.0
 */
- (NSArray *)               findInMOC:(NSManagedObjectContext *)aDifferentMOC
          similarObjectsForAttributes:(NSArray *)arrayOfNamesOfAttributes
                     forRelationships:(NSArray *)arrayOfNamesOfRelationships
         withAdditionalPredicate_cbd_:(NSPredicate *)additionalPredicate ;

/**
 Finds objects similar to self, according to attributes and relationships given in the arguments.
 You can specify additionnal constraints with additionalPredicate in a format version.
 
 Does the fetch in a MOC that you can specify.
 
 @warning This method works only if condition "`name(Class)=name(Entity)` or `mogenerator`" is satisfied
 
 @warning deprecated since v2.0.0
 */
- (NSArray *)               findInMOC:(NSManagedObjectContext *)aDifferentMOC
          similarObjectsForAttributes:(NSArray *)arrayOfNamesOfAttributes
                     forRelationships:(NSArray *)arrayOfNamesOfRelationships
   withAdditionalPredicateFormat_cbd_:(NSString *)formatString, ... NS_FORMAT_FUNCTION(4, 5) ;


@end
